global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'fever-monitoring-api'
    static_configs:
      - targets: ['host.docker.internal:8000'] # API port
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'mlflow-tracking'
    static_configs:
      - targets: ['host.docker.interval:5000'] # MLflow port

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
      - targets: []

      
